//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GaryBookstore.Web.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.BookAuthors = new HashSet<BookAuthor>();
            this.OrderDetails = new HashSet<OrderDetail>();
            this.Categories = new HashSet<Category>();
        }
    
        public int BookId { get; set; }
        public string GoogleBooksId { get; set; }
        public string Title { get; set; }
        public string Subtitle { get; set; }
        public string ISBN_13 { get; set; }
        public string ISBN_10 { get; set; }
        public string Publisher { get; set; }
        public System.DateTime PublishedDate { get; set; }
        public int PageCount { get; set; }
        public string Description { get; set; }
        public double AverageRating { get; set; }
        public int RatingsCount { get; set; }
        public decimal ListPrice { get; set; }
        public string Thumbnail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookAuthor> BookAuthors { get; set; }
        public virtual Cart Cart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Category> Categories { get; set; }
        public virtual Inventory Inventory { get; set; }
    }
}
